### ISSUE TITLE
Implement Tuple.java and TupleDesc.java

### ISSUE THREAD

**Issue by Priiyam** [manishsbhoopalam/SimpleDB#1]
## **Task 1**

**Implement the skeleton methods in:** 
src/java/simpledb/TupleDesc.java 
src/java/simpledb/Tuple.java 

**Objective:**
Code should pass the unit tests TupleTest and TupleDescTest.

**Comment by sbshah97** [comment]
Assign someone the Issues as well!

**Comment by Priiyam** [comment]
#7 Resolved
