### ISSUE TITLE
Implement InsertTuple and DeleteTuple methods

### ISSUE THREAD

**Issue by Rithesh17** [manishsbhoopalam/SimpleDB#14]
**Implement the skeleton methods in:**
src/simpledb/HeapPage.java
src/simpledb/HeapFile.java 

**Implement the following skeleton methods in src/simpledb/BufferPool.java:**
insertTuple()
deleteTuple()

**Objective:**
your code should pass the unit tests in HeapPageWriteTest and HeapFileWriteTest.

**Comment by sbshah97** [comment]
Is this Issue resolved?

**Comment by Rithesh17** [comment]
#25 and #26
