### ISSUE TITLE
Implement Insert.java and Delete.java

### ISSUE THREAD

**Issue by Rithesh17** [manishsbhoopalam/SimpleDB#17]
**Implement the skeleton methods in:**
src/simpledb/Insert.java
src/simpledb/Delete.java

**Objective:**
At this point, your code should pass the unit tests in InsertTest. Furthermore, you should be able to pass the InsertTest and DeleteTest system tests.

**Comment by sbshah97** [comment]
Is this Issue resolved?

**Comment by Ram-Aditya** [comment]
Yes.But we were waiting till all the files were approved and merged.

**Comment by Ram-Aditya** [comment]
Resolved.
