### ISSUE TITLE
Implement Aggregates

### ISSUE THREAD

**Issue by manishsbhoopalam** [manishsbhoopalam/SimpleDB#18]
**Implement the skeleton methods in:**
src/simpledb/IntegerAggregator.java
src/simpledb/StringAggregator.java
src/simpledb/Aggregate.java

**Objective:**
At this point, your code should pass the unit tests IntegerAggregatorTest, StringAggregatorTest, and AggregateTest. Furthermore, you should be able to pass the AggregateTest system test.

**Comment by sbshah97** [comment]
Is this Issue resolved?

**Comment by Ram-Aditya** [comment]
Yes.But we were waiting till all the files were approved and merged.

**Comment by Priiyam** [comment]
Resolved
