### ISSUE TITLE
Implement Filter and Join

### ISSUE THREAD

**Issue by manishsbhoopalam** [manishsbhoopalam/SimpleDB#19]
**Implement the skeleton methods in:**

    src/simpledb/Predicate.java
    src/simpledb/JoinPredicate.java
    src/simpledb/Filter.java
    src/simpledb/Join.java

**Objective:**
At this point, your code should pass the unit tests in PredicateTest, JoinPredicateTest, FilterTest, and JoinTest. Furthermore, you should be able to pass the system tests FilterTest and JoinTest.

**Comment by sbshah97** [comment]
Is this Issue resolved?
