### ISSUE TITLE
Implement BufferPool.java

### ISSUE THREAD

**Issue by Priiyam** [manishsbhoopalam/SimpleDB#3]
## **Task 3**

**Implement the skeleton methods in:** 
src/java/simpledb/BufferPool.java 

**NOTE:** Unit tests for BufferPool has not been provided

**Objective:**
The functionality implemented must be tested in the implementation of HeapFile. You should use the DbFile.readPage method to access pages of a DbFile.

**Comment by sbshah97** [comment]
Assign someone the Issues as well!

**Comment by Priiyam** [comment]
#10 resolved
