### ISSUE TITLE
Implement HeapFile

### ISSUE THREAD

**Issue by Priiyam** [manishsbhoopalam/SimpleDB#5]
## **Task 5**

**Implement the skeleton methods in:** 
src/java/simpledb/HeapFile.java 

**Objective:**
Code should pass the unit tests in HeapFileReadTest.

**Comment by Ram-Aditya** [comment]
@salman-bhai 
I was unable to figure out the code for DbFileIterator method.All four of us have tried but have failed to come up with a successful code.
We request your help on this method.
The current version of HeapFile has been attached.
[HeapFile.txt](https://github.com/manishsbhoopalam/SimpleDB/files/1080887/HeapFile.txt)

**Comment by sbshah97** [comment]
@Ram-Aditya there are some very small changes that you have to do in this file. :stuck_out_tongue: You are allowed to take help from your other friends in the Summer Project but don't lift their code. Discuss it with them and then implement it yourself!
